# Generated by Django 6.0.4 on 2026-04-29 11:18

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.BigAutoField(help_text='유저 고유 식별자', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='로그인 아이디로 사용하는 이메일', max_length=100, unique=True)),
                ('name', models.CharField(help_text='사용자 이름', max_length=60)),
                ('company_name', models.CharField(blank=True, help_text='사용자가 소속된 업체명', max_length=150, null=True)),
                ('position', models.CharField(blank=True, help_text='사용자의 직책', max_length=150, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('draft_id', models.BigAutoField(help_text='초안 고유 식별자', primary_key=True, serialize=False)),
                ('work_date', models.DateField(help_text='작업이 수행된 날짜')),
                ('task_name', models.CharField(blank=True, help_text='수행 작업명', max_length=100, null=True)),
                ('region_large', models.CharField(blank=True, help_text='작업 지역의 대분류', max_length=60, null=True)),
                ('region_middle', models.CharField(blank=True, help_text='작업 지역의 중분류', max_length=60, null=True)),
                ('region_detail', models.CharField(blank=True, help_text='작업 위치 상세 정보', max_length=100, null=True)),
                ('recording_text', models.TextField(blank=True, help_text='음성 인식 원문', null=True)),
                ('recording_duration_sec', models.IntegerField(blank=True, help_text='녹음 시간(초)', null=True)),
                ('draft_text', models.TextField(blank=True, help_text='생성된 작업 초안', null=True)),
                ('safety_guide_text', models.TextField(blank=True, help_text='안전 가이드', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='초안 생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='초안 마지막 수정 일시')),
                ('user', models.ForeignKey(db_column='user_id', help_text='초안을 작성한 유저 ID', on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drafts',
            },
        ),
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('weather_id', models.BigAutoField(help_text='날씨 정보 고유 식별자', primary_key=True, serialize=False)),
                ('weather_status', models.CharField(blank=True, help_text='날씨 상태', max_length=60, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='섭씨 기온', max_digits=4, null=True)),
                ('humidity', models.IntegerField(blank=True, help_text='습도(%)', null=True)),
                ('precipitation_probability', models.IntegerField(blank=True, help_text='강수확률(%)', null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, help_text='풍속(m/s)', max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='저장 일시')),
                ('draft', models.OneToOneField(db_column='draft_id', help_text='연결된 초안 ID', on_delete=django.db.models.deletion.CASCADE, to='account.draft')),
            ],
            options={
                'db_table': 'weather_info',
            },
        ),
    ]
