# Generated by Django 6.0.4 on 2026-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='호출한 AI 엔드포인트', max_length=200)),
                ('request_payload', models.JSONField(default=dict, help_text='요청 데이터')),
                ('response_payload', models.JSONField(default=dict, help_text='응답 데이터')),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP 상태 코드', null=True)),
                ('elapsed_ms', models.IntegerField(blank=True, help_text='응답 시간(ms)', null=True)),
                ('success', models.BooleanField(default=False, help_text='성공 여부')),
                ('error_message', models.TextField(blank=True, default='', help_text='에러 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='로그 생성 일시')),
            ],
            options={
                'db_table': 'ai_usage_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
