server {
    listen 80;
    server_name localhost;  # 서버 이름으로 (로컬 / EC2 IP / 도메인) 설정

    # 일반 요청은 Gunicorn(8000)으로 전달
    location / {
        proxy_pass         http://web:8000;
        proxy_set_header   Host              $host;
        # 클라이언트 IP와 프로토콜 정보 전달
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 120;
    }

    # 정적 파일
    location /static/ {
        alias /code/staticfiles/;
    }
}
